name: CI

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: 'Build and Push'
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     node-version: [16, 18, 20]

    steps:
      - uses: actions/checkout@v4
      # - name: Setup node | ${{ matrix.node-version }}
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          # node-version: ${{ matrix.node-version }}
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - run: npm test

      - name: Generate tag
        id: generate-tag
        run: |
          SHA=$(echo $GITHUB_SHA | head -c 7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.2.1
        with:
          role-to-assume: arn:aws:iam::143320676585:role/ecr-role
          aws-region: us-east-2

      - name: Amazon ECR Login
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2.0.1

      - name: Build docker image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry}}
          TAG: ${{ steps.generate-tag.outputs.sha }}
        run: |
          docker build -t $REGISTRY/luca-ci:$TAG .
          docker push $REGISTRY/luca-ci:$TAG
