name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: 'Build and Push'
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     node-version: [16, 18, 20]

    steps:
      - uses: actions/checkout@v4
      # - name: Setup node | ${{ matrix.node-version }}
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          # node-version: ${{ matrix.node-version }}
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - run: npm test

      - name: Generate tag
        id: generate-tag
        run: |
          SHA=$(echo $GITHUB_SHA | head -c 7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/luca-ci-api:${{ steps.generate-tag.outputs.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/luca-ci-api:latest

      # - name: Build docker image
      #   run: docker build -t local-image:latest .
      # - name: Tag docker image
      #   run: |
      #     docker tag local-image:latest ${{ secrets.DOCKERHUB_USERNAME }}/luca-ci-api:${{ steps.generate-tag.outputs.sha }}
      # - name: Push docker image
      #   run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/luca-ci-api:${{ steps.generate-tag.outputs.sha }}
